baseURL = "https://nifty-wiles-3ff3cc.netlify.com/"
languageCode = "cn-zh"
paginate = 6
summaryLength = "10"
theme = "parsa-hugo"
title = "韩诗语的小屋"
[[menu.main]]
URL = "about"
name = "关于我"
weight = 2
[[menu.main]]
URL = "contact"
name = "联系方式"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = ""
author = "韩诗语"
author_image = "images/mmexport1578789678652.jpg"
bio = "I’m an account living now in Singapore."
contact_form_action = "#"
copyright = "Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)"
description = "这里是诗语的小屋喔(●'◡'●)"
email = "han.shiyu@outlook.com"
google_analitycs_id = "Your ID"
home = "博客"
layout = "1"
logo = "images/logo.png"
mobile = ""
[params.instafeed]
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"
enable = true
user_id = "4044026246"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
[params.search]
enable = true
[[params.social]]
URL = "https://www.facebook.com/profile.php?id=100005283674963"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
[[params.social]]
URL = "#"
icon = "ti-linkedin"
[[params.social]]
URL = "https://github.com/hanshirley"
icon = "ti-github"
